[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
node_bundler = "esbuild"

# Fuerza a todas las funciones (incluido middleware) a usar Node.js
[functions."*"]
node_bundler = "esbuild"
included_files = [
  "next.config.ts",
  "middleware.ts",
  "lib/**",
  "app/**"
]
