export const themes = {
  'petali-rosa': {
    name: 'Pétalos de Rosa',
    light: {
      primary: '#A62454',
      primaryForeground: '#ffffff',
      secondary: '#F2C9E4',
      secondaryForeground: '#8C0327',
      accent: '#D95B96',
      accentForeground: '#ffffff',
      background: '#F6F1F3',
      foreground: '#8C0327',
      card: '#ffffff',
      cardForeground: '#8C0327',
      border: '#EAC4C9',
      input: '#EAC4C9',
      ring: '#A62454',
      muted: '#F2C9E4',
      mutedForeground: '#8C0327',
    },
    dark: {
      primary: '#D95B96',
      primaryForeground: '#ffffff',
      secondary: '#8C0327',
      secondaryForeground: '#F2C9E4',
      accent: '#F2A7D0',
      accentForeground: '#8C0327',
      background: '#1a0a0f',
      foreground: '#F2C9E4',
      card: '#2d1420',
      cardForeground: '#F2C9E4',
      border: '#8C0327',
      input: '#8C0327',
      ring: '#D95B96',
      muted: '#8C0327',
      mutedForeground: '#F2C9E4',
    }
  },
  'damask-rose': {
    name: 'Rosa Damascena',
    light: {
      primary: '#F26DAB',
      primaryForeground: '#ffffff',
      secondary: '#F2D5EA',
      secondaryForeground: '#613C5F',
      accent: '#F29BCB',
      accentForeground: '#ffffff',
      background: '#F2F2F2',
      foreground: '#613C5F',
      card: '#ffffff',
      cardForeground: '#613C5F',
      border: '#F2B6D7',
      input: '#F2B6D7',
      ring: '#F26DAB',
      muted: '#F2D5EA',
      mutedForeground: '#613C5F',
    },
    dark: {
      primary: '#F29BCB',
      primaryForeground: '#ffffff',
      secondary: '#613C5F',
      secondaryForeground: '#F2D5EA',
      accent: '#F2B6D7',
      accentForeground: '#613C5F',
      background: '#1a1418',
      foreground: '#F2D5EA',
      card: '#2d2328',
      cardForeground: '#F2D5EA',
      border: '#BC92A9',
      input: '#BC92A9',
      ring: '#F29BCB',
      muted: '#613C5F',
      mutedForeground: '#F2B6D7',
    }
  },
  'cyber-tech': {
    name: 'Cyber Tech',
    light: {
      primary: '#148DD9',
      primaryForeground: '#ffffff',
      secondary: '#73CFD9',
      secondaryForeground: '#081526',
      accent: '#36ABD9',
      accentForeground: '#ffffff',
      background: '#f0f9ff',
      foreground: '#081526',
      card: '#ffffff',
      cardForeground: '#081526',
      border: '#73CFD9',
      input: '#73CFD9',
      ring: '#148DD9',
      muted: '#73CFD9',
      mutedForeground: '#081526',
    },
    dark: {
      primary: '#36ABD9',
      primaryForeground: '#ffffff',
      secondary: '#081526',
      secondaryForeground: '#73CFD9',
      accent: '#52F2F2',
      accentForeground: '#081526',
      background: '#041326',
      foreground: '#73CFD9',
      card: '#081526',
      cardForeground: '#73CFD9',
      border: '#35748C',
      input: '#35748C',
      ring: '#36ABD9',
      muted: '#35748C',
      mutedForeground: '#73CFD9',
    }
  },
  'purple-gradient': {
    name: 'Púrpura Elegante',
    light: {
      primary: '#5B6BE5',
      primaryForeground: '#ffffff',
      secondary: '#CFB7FE',
      secondaryForeground: '#3d2b59',
      accent: '#A364D0',
      accentForeground: '#ffffff',
      background: '#faf9fe',
      foreground: '#3d2b59',
      card: '#ffffff',
      cardForeground: '#3d2b59',
      border: '#CFB7FE',
      input: '#CFB7FE',
      ring: '#5B6BE5',
      muted: '#CFB7FE',
      mutedForeground: '#3d2b59',
    },
    dark: {
      primary: '#A364D0',
      primaryForeground: '#ffffff',
      secondary: '#3d2b59',
      secondaryForeground: '#CFB7FE',
      accent: '#5B6BE5',
      accentForeground: '#ffffff',
      background: '#1a1525',
      foreground: '#CFB7FE',
      card: '#2d243a',
      cardForeground: '#CFB7FE',
      border: '#5B6BE5',
      input: '#5B6BE5',
      ring: '#A364D0',
      muted: '#5B6BE5',
      mutedForeground: '#CFB7FE',
    }
  },
  'ai-neural': {
    name: 'IA Neural',
    light: {
      primary: '#0B368C',
      primaryForeground: '#ffffff',
      secondary: '#148DD9',
      secondaryForeground: '#061440',
      accent: '#D50DD9',
      accentForeground: '#ffffff',
      background: '#f5f7fa',
      foreground: '#061440',
      card: '#ffffff',
      cardForeground: '#061440',
      border: '#148DD9',
      input: '#148DD9',
      ring: '#0B368C',
      muted: '#148DD9',
      mutedForeground: '#061440',
    },
    dark: {
      primary: '#148DD9',
      primaryForeground: '#ffffff',
      secondary: '#061440',
      secondaryForeground: '#148DD9',
      accent: '#D50DD9',
      accentForeground: '#ffffff',
      background: '#041326',
      foreground: '#148DD9',
      card: '#061440',
      cardForeground: '#148DD9',
      border: '#0B368C',
      input: '#0B368C',
      ring: '#148DD9',
      muted: '#0B368C',
      mutedForeground: '#148DD9',
    }
  },
} as const

export type ThemeKey = keyof typeof themes
export type ThemeMode = 'light' | 'dark'